# Use root/example as user/password credentials
version: '3.8'
services:
  stock-market-api:
    image: stock-market-api:latest
    build:
      context: .
    container_name: stock-market-api
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - QUEUE_URL=${QUEUE_URL}
    restart: unless-stopped