spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: c3bN5JhM5LWPtetkKmFXXPcWgMrvd3C5 #123456
    url: jdbc:mysql://${DB_URL}:3306/STOCK_MARKET_DB?createDatabaseIfNotExist=true
    #jdbc:mysql://localhost:3306/stockMarketDB?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  rabbitmq:
    host: ${QUEUE_URL} #localhost
    port: 5672
    username: guest #admin
    password: guest #123456
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics